language: python
sudo: false
os:
  - linux
cache:
    pip: true
python:
  - 3.6
install:
  - pip install coveralls flake8
  - pip install .
script:
  - flake8 . --ignore=F403,E501,E123,E128,F401,W504 --exclude=build
  - nosetests --with-coverage --cover-package=economicsl
after_success:
  - coveralls
